// SPDX-License-Identifier: Apache-2.0
import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';

const base = '/books/understanding-llms';
const locales = ['en', 'zh-hans'];
const release = JSON.parse(readFileSync(new URL('../data/releases/2026-09-15-publication.json', import.meta.url), 'utf8'));
const available: string[] = [...release.previous_published_ids, ...release.promoted_ids];

for (const locale of locales) {
  test(`${locale}: published home, complete roadmap and excluded placeholders`, async ({ page, request }, info) => {
    test.skip(process.env.BOOK_RELEASE_CHECK !== '1', 'Requires the built production artifact.');
    await page.goto(`${base}/${locale}/`);
    await expect(page.locator('main')).toContainText(locale === 'en' ? 'Chapters 1–39 and 54–57 are available' : '第 1—39 章及第 54—57 章已开放阅读');
    await expect(page.locator('main a[href$="/primer-py/"]')).toHaveCount(1);
    expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1);
    await page.screenshot({ path: info.outputPath('published-home.png'), animations: 'disabled' });
    await page.goto(`${base}/${locale}/roadmap/`);
    const content = page.locator('.sl-markdown-content');
    for (const id of available) {
      await expect(content.locator(`a[href$="/${id}/"]`)).toHaveCount(1);
    }
    for (const id of release.remaining_drafts) {
      await expect(page.locator(`a[href$="/${id}/"]`)).toHaveCount(0);
      expect((await request.get(`${base}/${locale}/${id}/`)).status(), id).toBe(404);
    }
    expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1);
    await page.screenshot({ path: info.outputPath('published-roadmap.png'), animations: 'disabled' });
  });

  test(`${locale}: real search finds a newly published chapter`, async ({ page }, info) => {
    test.skip(process.env.BOOK_RELEASE_CHECK !== '1', 'Search is generated by the production build.');
    await page.goto(`${base}/${locale}/`);
    await page.locator('site-search button[data-open-modal]').click();
    await page.locator('site-search').getByRole('textbox').fill(locale === 'en' ? 'Capstone' : '毕业项目');
    const result = page.locator(`site-search a[href*="/${locale}/ch-57/"]`).first();
    await expect(result).toBeVisible();
    await page.screenshot({ path: info.outputPath('published-search.png'), animations: 'disabled' });
    await result.click();
    await expect(page).toHaveURL(new RegExp(`/${locale}/ch-57/(?:#.*)?$`));
    await expect(page.locator('main h1 .book-chapter-label')).toHaveText(locale === 'en' ? 'Chapter 57' : '第 57 章');
  });
}
