// SPDX-License-Identifier: Apache-2.0
import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';

const base = '/books/understanding-llms';
const locales = ['en', 'zh-hans'];
const release = JSON.parse(readFileSync(new URL('../data/releases/2026-09-15-complete-publication.json', import.meta.url), 'utf8'));
const available: string[] = [...release.previous_published_ids, ...release.promoted_ids];

for (const locale of locales) {
  test(`${locale}: published home, complete roadmap and excluded placeholders`, async ({ page, request }, info) => {
    test.skip(process.env.BOOK_RELEASE_CHECK !== '1', 'Requires the built production artifact.');
    await page.goto(`${base}/${locale}/`);
    await expect(page.locator('main')).toContainText(locale === 'en' ? 'All 57 chapters and both primers are available' : '全书 57 章及两份基础补充已开放阅读');
    await expect(page.locator('main a[href$="/primer-py/"]')).toHaveCount(1);
    await expect(page.locator('main a[href$="/primer-http/"]')).toHaveCount(1);
    expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1);
    await page.screenshot({ path: info.outputPath('published-home.png'), animations: 'disabled' });
    await page.goto(`${base}/${locale}/roadmap/`);
    const content = page.locator('.sl-markdown-content');
    for (const id of available) {
      await expect(content.locator(`a[href$="/${id}/"]`)).toHaveCount(1);
    }
    for (const id of release.remaining_drafts) {
      await expect(page.locator(`a[href$="/${id}/"]`)).toHaveCount(0);
      expect((await request.get(`${base}/${locale}/${id}/`)).status(), id).toBe(404);
    }
    expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1);
    await page.screenshot({ path: info.outputPath('published-roadmap.png'), animations: 'disabled' });
  });

  for (const target of ['ch-53', 'primer-http']) test(`${locale}: real search finds ${target}`, async ({ page }, info) => {
    test.skip(process.env.BOOK_RELEASE_CHECK !== '1', 'Search is generated by the production build.');
    await page.goto(`${base}/${locale}/`);
    await page.locator('site-search button[data-open-modal]').click();
    const query = target === 'ch-53' ? (locale === 'en' ? 'Tenant Isolation' : '供应链') : 'Retry-After';
    await page.locator('site-search').getByRole('textbox').fill(query);
    const result = page.locator(`site-search a[href*="/${locale}/${target}/"]`).first();
    await expect(result).toBeVisible();
    await page.screenshot({ path: info.outputPath('published-search.png'), animations: 'disabled' });
    await result.click();
    await expect(page).toHaveURL(new RegExp(`/${locale}/${target}/(?:#.*)?$`));
    if (target === 'ch-53') await expect(page.locator('main h1 .book-chapter-label')).toHaveText(locale === 'en' ? 'Chapter 53' : '第 53 章');
    else await expect(page.locator('main h1')).toContainText('HTTP');
  });
}

test('zh-hans: compound query finds its exact chapter title (known Pagefind limitation)', async ({ page }) => {
  test.skip(process.env.BOOK_RELEASE_CHECK !== '1', 'Search is generated by the production build.');
  test.fail(true, 'Pagefind 1.5.2 indexes the compound as one word; Chrome 153 splits it into two. See the complete-core release record.');
  await page.goto(`${base}/zh-hans/`);
  await page.locator('site-search button[data-open-modal]').click();
  await page.locator('site-search').getByRole('textbox').fill('租户隔离');
  await expect(page.locator('site-search a[href*="/zh-hans/ch-53/"]').first()).toBeVisible();
});
