// SPDX-License-Identifier: Apache-2.0
import { test, expect } from '@playwright/test';

const base = '/books/understanding-llms';
const locales = ['en', 'zh-hans'];

for (const locale of locales) {
  test(`${locale}: published home, complete roadmap and excluded placeholders`, async ({ page, request }, info) => {
    test.skip(process.env.BOOK_RELEASE_CHECK !== '1', 'Requires the built production artifact.');
    await page.goto(`${base}/${locale}/`);
    await expect(page.locator('main')).toContainText(locale === 'en' ? 'Chapters 1–39 are available' : '第 1—39 章已开放阅读');
    await expect(page.locator('main a[href$="/primer-py/"]')).toHaveCount(1);
    expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1);
    await page.screenshot({ path: info.outputPath('published-home.png'), animations: 'disabled' });
    await page.goto(`${base}/${locale}/roadmap/`);
    const content = page.locator('.sl-markdown-content');
    for (let number = 1; number <= 39; number++) {
      const id = `ch-${String(number).padStart(2, '0')}`;
      await expect(content.locator(`a[href$="/${id}/"]`)).toHaveCount(1);
    }
    await expect(content.locator('a[href$="/primer-py/"]')).toHaveCount(1);
    const excluded = [...Array.from({length:18}, (_, index) => `ch-${index + 40}`), 'primer-http', 'ext-mm-01'];
    for (const id of excluded) {
      await expect(page.locator(`a[href$="/${id}/"]`)).toHaveCount(0);
      expect((await request.get(`${base}/${locale}/${id}/`)).status(), id).toBe(404);
    }
    expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1);
    await page.screenshot({ path: info.outputPath('published-roadmap.png'), animations: 'disabled' });
  });

  test(`${locale}: real search finds a newly published chapter`, async ({ page }, info) => {
    test.skip(process.env.BOOK_RELEASE_CHECK !== '1', 'Search is generated by the production build.');
    await page.goto(`${base}/${locale}/`);
    await page.locator('site-search button[data-open-modal]').click();
    await page.locator('site-search').getByRole('textbox').fill(locale === 'en' ? 'QLoRA' : '低秩');
    const result = page.locator(`site-search a[href*="/${locale}/ch-39/"]`).first();
    await expect(result).toBeVisible();
    await page.screenshot({ path: info.outputPath('published-search.png'), animations: 'disabled' });
    await result.click();
    await expect(page).toHaveURL(new RegExp(`/${locale}/ch-39/(?:#.*)?$`));
    await expect(page.locator('main h1 .book-chapter-label')).toHaveText(locale === 'en' ? 'Chapter 39' : '第 39 章');
  });
}
